version: '3.8'
networks:
  monitor-net:
    driver: bridge
volumes:
    prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:\prometheus-2.22.1.windows-amd64\
      - prometheus_data:\prometheus-2.22.1.windows-amd64
    command:
      - '--config.file=prometheus-2.22.1.windows-amd64/prometheus.yml'
      - '--storage.tsdb.path=\prometheus-2.22.1.windows-amd64'
      - '--web.console.libraries=\prometheus-2.22.1.windows-amd64console_libraries'
      - '--web.console.templates=\prometheus-2.22.1.windows-amd64\consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    # restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net